steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'agroconect-servicehub'  # Your Cloud Run service name
    - '--image=us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agroconect-servicehub' # UPDATED IMAGE FORMAT
    - '--region=us-west1'      # The region where your Cloud Run service will be deployed
    - '--source=.'             # Tells gcloud to build from source using Buildpacks
    - '--platform=managed'     # Specifies Google-managed Cloud Run platform
    - '--allow-unauthenticated' # OPTIONAL: Remove this if your service requires authentication
  id: Deploy to Cloud Run
images:
- 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agroconect-servicehub' # UPDATED IMAGE FORMAT
options:
  logging: CLOUD_LOGGING_ONLY


